### ISSUE TITLE
Research: How do we set up our pages with LiveView?

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/dpul-collections#112]
## Acceptance Criteria

- [ ] Determine how we decide if a page should be a LiveView or have a controller.
- [ ] Report findings to the team.

## First Step

Do some searching and reading of documentation or opinions.

Some examples:

https://elixirforum.com/t/liveview-for-everything/52385/5
https://elixirforum.com/t/is-it-possible-in-liveview-0-17-9-to-use-it-for-only-part-of-the-page/47260

**Comment by hackartisan** [comment]
This is a very relevant thread: https://elixirforum.com/t/do-you-still-have-deadviews-accompanying-liveviews/51716/31
