### ISSUE TITLE
Measure time to hydrate, transform, index

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/dpul-collections#115]
We have requirements on how fast we have to be able to fully perform each of these steps. We need to know whether we're meeting those requirements.

Other things to think about:
- Do we want to collect stats on this in an ongoing way? I.e. will we want to know how long it took last time? last month? E.g. if there were a lot of network errors during the last run, the timing we see might be anomalous.
- Will it be relevant how many records were hydrated / transformed / indexed, or do we only care about how long it took?
- We'll have to define how we know when we're done. Maybe we record some ID at startup and then check whether we hit that ID?
- Potentially related to the "validate we got everything" ticket, #46 

## Acceptance Criteria
- [ ] There is some page I can go to or log message I can find that says how long each of these steps took the last time it ran

**Comment by tpendragon** [comment]
Brainstorming a bit:

Some possibly useful metrics I can think of are:

1. Time to Poll - this is how long it takes on a fresh start-up for the Hydrator to hit polling, then how long from that point for each stage after that to catch up to its last thing. Seems hard.
2. Time to Process 1 Doc. Seems like we'd have to record what the doc is, and then notify when it came out of the indexing consumer.
3. Throughput - records/s
