### ISSUE TITLE
DPUL-Collections machines should network with one another

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/dpul-collections#118]
Connecting the machines via Elixir networking will let Phoenix.PubSub, Phoenix.Presence, and LiveView be aware of multiple machines and share information automatically. It'll also let us write distributed software in the future.

## Acceptance Criteria

- [ ] `Node.list()` on one DPUL-C node returns the address of the other nodes that are launched.

## First Step

So much research.

## Technical Tips

(This was written after the fact, I'm mostly writing it here to include some info)
1. You can generate setup files for releases via `mix release.init`
1. Releases need a name, defined by `RELEASE_NODE`.
1. RELEASE_DISTRIBUTION needs to be `name`
1. https://github.com/phoenixframework/dns_cluster expects nodes to be named `<app name>@<machine ip>`
1. Erlang usually uses EPMD (Erlang Port Mapper Daemon) for networking, which is a daemon that runs on port 4369 and records a random high-number port for each erlang VM on the machine that other erlang VMs should use for distributed traffic.
1. You can turn off EPMD and instead just set the port used for distributed traffic by setting `-start_epmd false -erl_epmd_port 6789`.
1. We can rely on consul for DNS discovery of new nodes, but to do so containers need to be able to run consul queries. We can do that by setting the container's DNS to be the machine it's running on (which has a running consul DNS interface.)

**Comment by hackartisan** [comment]
elixir in action 12.3 does provide some relevant background.

fwiw, it doesn't talk about turning off EPMD or setting a single port for the node. It talks about setting `inet_dist_listen_min` and `inet_dist_listen_max` and setting those to the same number if you want to have your node always use the same port.
