### ISSUE TITLE
Add internationalization

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/dpul-collections#123]
### Acceptance criteria
- [x] gettext is in the deps
- [x] there's documentation in our readme about how to use it when you're adding a string in a template
- [x] there's documentation on what to do if you edit a string
- [x] The home page text is translated to one language - spanish.
- [x] The language dropdown works.

## First Step

Read the gettext getting started documentation.

## Technical Implementation Tips

We'll probably have to wrap the text in the home page that's there now in some kind of gettext tag.

**Comment by sdellis** [comment]
Inspiration for Plug code: https://github.com/goofansu/locale_plug/blob/main/lib/locale_plug.ex

Look at Restore Locale code so we can by DRY:
https://hexdocs.pm/phoenix_live_view/using-gettext.html

**Comment by sdellis** [comment]
Current translations: https://github.com/pulibrary/lae-blacklight/tree/main/config/locales
