### ISSUE TITLE
Implement show page wireframe

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/dpul-collections#124]
## Acceptance Criteria

- [ ] Going to the url for a record (`/item/:id`) results in a view that looks like below.

## First Step

Create a route and live view for a record page. 

## Wireframe Notes

The big box should be a big preview image generated by a random image generator - we recommend https://random-d.uk/api/randomimg, but go with your heart.

Every little box should also be a random image. Again, ducks are cute.

The download link should link to a download of the image. In this case...I guess another random duck picture.

## Wireframes

Full screen view:
![dpul-c-record-wireframe4](https://github.com/user-attachments/assets/f53a1ba1-46d6-4f9b-9182-1156ec26b14d)

Mobile view:
![dpul-c-record-page-mobile2](https://github.com/user-attachments/assets/b8d029f6-e5b5-45d6-8ff1-850c5657594f)

**Comment by sdellis** [comment]
Updated to include `Download` and `View` buttons. Since individual pages are downloadable, this seems logical. View would open the item in a viewer.

![dpul-c-record-wireframe3](https://github.com/user-attachments/assets/36fb1390-cdd4-4773-82ce-1827d41b9434)

**Comment by sdellis** [comment]
Mobile view:
![dpul-c-record-page-mobile-wireframe](https://github.com/user-attachments/assets/4a7d0061-7834-40cb-a84e-8b91306235b8)

**Comment by sdellis** [comment]
Final wireframe for 1st "slice" Record Page.

Full screen view:
![dpul-c-record-wireframe4](https://github.com/user-attachments/assets/f53a1ba1-46d6-4f9b-9182-1156ec26b14d)

Mobile view:
![dpul-c-record-page-mobile2](https://github.com/user-attachments/assets/b8d029f6-e5b5-45d6-8ff1-850c5657594f)

**Comment by sdellis** [comment]
Implements #29

**Comment by hackartisan** [comment]
Still needed: Description, larger font for title and in general for heading fonts
