### ISSUE TITLE
Implement home page slice wireframe

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/dpul-collections#125]
## Acceptance Criteria

- [x] The root URL looks roughly like the wireframe below.
- [ ] ~~the header / footer are included via the app layout rather than the root layout~~

## First Step

Create a route and live view for the home page.

## Wireframe
![375095301-687a564f-e591-4381-a134-82cd7d3bbeb8](https://github.com/user-attachments/assets/335bba4d-0a60-4e73-910f-477d8c896c41)

**Comment by sdellis** [comment]
Mobile wireframe:
![dpul-c-homepage-mobile](https://github.com/user-attachments/assets/c9f1174a-7e69-4f12-8f31-69a8aff8582d)

**Comment by sdellis** [comment]
Implements #27

**Comment by sdellis** [comment]
Reopened because it doesn't meet the acceptance criteria. This uses the root layout due to technical limitations.

**Comment by sdellis** [comment]
Search box/button need further styling. 

Current screenshot: 
<img width="1196" alt="Screenshot 2024-10-17 at 4 31 36 PM" src="https://github.com/user-attachments/assets/81d35c7c-d221-4678-8296-f3f8d4201bbe">

**Comment by hackartisan** [comment]
> Reopened because it doesn't meet the acceptance criteria. This uses the root layout due to technical limitations.

I'm fine removing that acceptance criteria, given it came up against technical issues. I'll add a note to #133

**Comment by hackartisan** [comment]
Still needed: Make the text centered and a bit larger
