### ISSUE TITLE
Add title slug into show page routes

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/dpul-collections#126]
## Acceptance Criteria

- [x] URLs generated for going to item pages should look like `/i/:slug/item/:id`

## Reasoning

When sharing the URL we think it would be nice if folks had an idea of what they're clicking before they click it. Further, google really likes when URLs have text in them.

## First Step

Write a test

**Comment by eliotjordan** [comment]
Complete.

**Comment by hackartisan** [comment]
added in https://github.com/pulibrary/dpul-collections/pull/195; follow up issue is https://github.com/pulibrary/dpul-collections/issues/205
