### ISSUE TITLE
Index dates for Ephemera Folders

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/dpul-collections#134]
## Acceptance Criteria

- [ ] There's a years field in the solr document that has all of the years in an array that should match.
- [ ] There's a display_date field in the solr document that is what will render in the record page.

## Implementation Note

The suffix isn't defined above, part of the ticket is figuring out which suffixes are appropriate for each field.

suffixes to use:
- display field should be string, `display_date_ss`
- years field, used for sorting, searching, and faceting, should be integer, `years_is`.

**Comment by hackartisan** [comment]
There is validation on the date range in figgy, but there's nothing saying you can only have a date_created or a date range. there's some discussion of this on https://github.com/pulibrary/figgy/pull/302 but it looks like further work got ice boxed.

I'm planning to use the date range if it's there, and if not use date created.
