### ISSUE TITLE
Implement search results page wireframe

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/dpul-collections#135]
## Acceptance Criteria

- [ ] The root URL looks roughly like the wireframe below.

## First Step

Create a route and live view for the search page.

## Wireframe
https://github.com/pulibrary/dpul-collections/issues/28

## Follow up tickets
- #139
- #140

**Comment by sdellis** [comment]
Final wireframes for 1st "slice" Search Results:

Full screen view:
![dpul-c-searchresults-wireframe10](https://github.com/user-attachments/assets/d8cd4876-ead8-433e-b19d-31bfa7907547)

Mobile view:
![dpul-c-search-results-mobile](https://github.com/user-attachments/assets/f9f52976-01df-43a0-b384-e626d72fcaf2)

**Comment by sdellis** [comment]
Add the "Apply" button to the date filters before we close this out.

**Comment by sdellis** [comment]
<img width="1165" alt="Screenshot 2024-11-11 at 4 02 27 PM" src="https://github.com/user-attachments/assets/56debea3-0289-43fb-a59b-985dc7448793">
