### ISSUE TITLE
Add phoenix and broadway dashboards

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/dpul-collections#155]
Having access to the dashboards will help us understand our system and our stack.

# Acceptance Criteria
- [x] phoenix livedashboard is installed and accessible in our development environment
- [ ] the broadway dashboard is installed and accessible in our development environment
- [ ] phoenix livedashboard is installed and accessible in our staging environment
- [ ] the broadway dashboard is installed and accessible in our staging environment
- [ ] the dashboards are protected by some kind of auth? phoenix gives instructions for basic auth: https://hexdocs.pm/phoenix_live_dashboard/Phoenix.LiveDashboard.html#module-extra-add-dashboard-access-on-all-environments-including-production

# First step
Follow installation instructions:
- https://hexdocs.pm/phoenix_live_dashboard/Phoenix.LiveDashboard.html
- https://github.com/dashbitco/broadway_dashboard/

**Comment by tpendragon** [comment]
The dashboard's already installed in dev.
