### ISSUE TITLE
Update console script to allow connecting to an indexer

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/dpul-collections#193]

**Comment by hackartisan** [comment]
I think we could maybe use [consul catalog nodes with the service option](https://developer.hashicorp.com/consul/commands/catalog/nodes#service) and potentially also the node-type meta to find the id of the node that we need to connect to. node meta was added in this PR: https://github.com/pulibrary/princeton_ansible/pull/5487/files

Then maybe once we had that we could run the ssh command on that box. 

But I can't get that command to output anything on any of the nomad boxes.

**Comment by hackartisan** [comment]
I was able to make some stuff work by using the auth tokens. I wanted to use a nomad command to get the id of the node that had the index on it. the most promising seemed to be to use the service name (well, first set it then use it), but the service name we are setting currently in hcl doesn't seem to come through. here's what I tried: 
```
ssh -t deploy@nomad-host-prod1.lib.princeton.edu "curl --header \"Authorization: Bearer redacted\" http://localhost:4646/v1/service/dpulc-staging-web" | jq                                                                                                          
[]
```

it's awkward to ssh first to the machine and then curl localhost but i was getting some tls errors submitting the curl directly.

**Comment by tpendragon** [comment]
@hackartisan I think this works now if you do

```
JOBTASK=indexer ./bin/console staging repl
```

a few times. Sometimes it errors, because `nomad alloc exec -job` picks a random allocation, and only one of the allocations is running the indexer. It'd be good to make it so it instead passes an allocation ID for the indexer task, but I'm not sure how to do that. Maybe parsing `nomad status dpulc-staging` somehow?
