### ISSUE TITLE
DPUL-C Home Page Wireframe - Slice 1

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/dpul-collections#27]
## Acceptance Criteria

- [ ] There's a picture for the desktop view.
- [ ] There's a picture for the mobile view.

## Wireframe Requirements

- There's a search bar, and a way to submit that search.
- There's a header and footer.
- There's a language switcher.

**Comment by sdellis** [comment]
![dpul-c-homepage-wireframe](https://github.com/user-attachments/assets/687a564f-e591-4381-a134-82cd7d3bbeb8)

**Comment by sdellis** [comment]
Mobile view:
 
![dpul-c-homepage-mobile](https://github.com/user-attachments/assets/13790e1a-b14c-455e-a5db-04f157755238)
