### ISSUE TITLE
Search Results Wireframe

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/dpul-collections#28]
## Acceptance Criteria

- [x] There should be a picture for the desktop view.
- [x] There should be a picture for the mobile view.
- [x] There should be a way to filter to a date range
- [x] There should be a way to sort by date and relevance.

# Wireframe Requirements

List of records with the following:

- [x] Title Display
- [x] Thumbnail
- [x] Link to record

**Comment by sdellis** [comment]
Search Results View:

![dpul-c-searchresults-wireframe10](https://github.com/user-attachments/assets/483bd3f2-8773-4e24-aaae-a328a575c89c)
