### ISSUE TITLE
Show Page Wireframe for Ephemera

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/dpul-collections#29]
Also known as the "Record Page"

## Acceptance Criteria

- [x] There's a picture for the desktop view
- [x] There's a picture for the mobile view

## Wireframe Requirements

- [x] Display images nicely
- [ ] Easy way to copy a view of a resource - e.g page 6, zoomed in at this position.
- [x] Download
- [x] There's a title.
- [x] There's a description.
- [x] Some way to display metadata, we'll have date.

**Comment by sdellis** [comment]
![dpul-c-record-wireframe2](https://github.com/user-attachments/assets/abca56a9-42c9-4b9b-aa3f-bb6b01dab14b)

**Comment by sdellis** [comment]
Adds Download and View buttons. If View is not needed, Download can fill the space.

![dpul-c-record-wireframe3](https://github.com/user-attachments/assets/a5f03e79-3a2f-4bb3-b9dd-ef6c31c307e4)

**Comment by sdellis** [comment]
Mobile view:

![dpul-c-record-page-mobile-wireframe](https://github.com/user-attachments/assets/486fa7c8-60b1-4a73-80ee-d34f591fa990)

**Comment by sdellis** [comment]
@hackartisan suggested for the first "slice" the View button should be a Copy Link button so users can paste into an email, etc.

**Comment by sdellis** [comment]
Here are the final record page wireframes for the first "slice".

Full screen view:
![dpul-c-record-wireframe4](https://github.com/user-attachments/assets/11a4d209-c7f1-48ce-ab8d-67421bc03d8c)

Mobile view:
![dpul-c-record-page-mobile2](https://github.com/user-attachments/assets/de7bf48b-a7f7-4fc4-b32d-9dbbd12f35ed)

**Comment by hackartisan** [comment]
We removed the requirement for `Easy way to copy a view of a resource - e.g page 6, zoomed in at this position.` because we aren't planning that implementation for this slice.
