### ISSUE TITLE
Develop an Indexing Pipeline

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/dpul-collections#30]
This will have a bunch of sub-issues, this is mostly to record the fact that we need to make this.

## Acceptance Criteria

- [x] #41
- [x] #42
- [x] #43
- [x] #44
- [x] #45
    * Indexing phase should not kill Solr. Have some way to throttle traffic to Solr.
- [ ] #46
- [x] #47

## First Step

Split those tickets up up there.

Finalize the ADR: https://github.com/pulibrary/dpul-collections/pull/34

## Architecture Discussions

https://docs.google.com/document/d/1VgYeonai-q4NI6yXK0n3rYAipDsHH7j85C3XxoP-W6E/edit#heading=h.8n3o7dn0pcfs

## Content

All public Ephemera resources that are images

**Comment by hackartisan** [comment]
close and let #46 stand on its own.
