### ISSUE TITLE
Develop the Indexing Phase

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/dpul-collections#45]
## Success Criteria

The process described in the [ADR Indexing Phase](https://github.com/pulibrary/dpul-collections/blob/main/architecture-decisions/0002-indexing.md#indexing) is implemented and tested.

This means we have a process which takes the items in the TransformationLog table and stores them in Solr.

## First Step

Review the ADR requirements.

**Comment by hackartisan** [comment]
done in #85
