### ISSUE TITLE
Add tests for figgy producer edge cases

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/dpul-collections#64]
## Acceptance Criteria

1. Specifically set the timestamps for the figgy resources that are hard-coded into our tests.
2. Specifically set some timestamps to be identical in a way that will enable us to test the 2nd scenario documented for `lib/dpul_collections/indexing_pipeline.ex#get_figgy_resources_since!`
3. Write tests to use those newly-enhanced records
4. Document the fact that our fixtures are manipulated in this way, and how to ensure any new tests written that use the figgy db fixtures will be similarly locked down.

## Implementation considerations

One way to do this would be to write it into the database fixture build script. But then you have to rebuild the container to add new tests of this variety.

An alternative to doing this in the fixture build script could be to write a before suite hook that updates the timestamps before the tests run. This would mean we have to turn off readonly mode for the figgy repo when running in the test environment. We like this idea best, try it first.

**Comment by tpendragon** [comment]
We've tested the edge cases we need to.
