### ISSUE TITLE
Refactor indexing_pipeline.ex

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/dpul-collections#82]
This file is big. What is the best way to split it up? Maybe a separate file for queries corresponding to each schema? Will we want some of these under the `figgy` namespace?
 
## Acceptance Criteria

- [ ] Common decision on the best way to split it up.
- [ ] The file is smaller and we're happy with it.

## First Step

- Talk about it in Ensemble.

**Comment by hackartisan** [comment]
I'm kind of used to it at this point. Maybe it's fine and we just close this issue?

**Comment by tpendragon** [comment]
We've decided we're fine with it.
